{% set version = '0.1.5' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gglogo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gglogo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gglogo/gglogo_{{ version }}.tar.gz
  sha256: 1416379745ea69b1707d9fe3e7411b2a763aadae94b6652e64bfe9c9b6068f23

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-knitr
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-reshape2
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-knitr
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-reshape2
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('gglogo')"           # [not win]
    - "\"%R%\" -e \"library('gglogo')\""  # [win]

about:
  home: https://github.com/heike/gglogo
  license: GPL-3.0-only
  summary: Visualize sequences in (modified) logo plots. The design choices used by these logo
    plots allow sequencing data to be more easily analyzed. Because it is integrated
    into the 'ggplot2' geom framework, these logo plots support native features such
    as faceting.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gglogo
# Title: Geom for Logo Sequence Plots
# Version: 0.1.5
# Authors@R: c( person("Heike", "Hofmann", email = "hofmann@iastate.edu", role = "aut"), person("Eric", "Hare", email = "eric@oaiti.org", role = c("aut", "cre")), person("GGobi Foundation", role = "aut"))
# License: GPL-3
# URL: https://github.com/heike/gglogo
# BugReports: https://github.com/heike/gglogo/issues
# Depends: R (>= 3.6)
# Imports: ggplot2 (>= 2.0.0), grid, jpeg, plyr, dplyr, tidyr, magrittr, purrr, reshape2, knitr, rlang
# Suggests: RColorBrewer
# Description: Visualize sequences in (modified) logo plots. The design choices used by these logo plots allow sequencing data to be more easily analyzed. Because it is integrated into the 'ggplot2' geom framework, these logo plots support native features such as faceting.
# Collate: 'logos.r' 'text.r' 'thin.r' 'data.r' 'alphabet.r' 'position.r'
# RoxygenNote: 7.0.2
# Encoding: UTF-8
# VignetteBuilder: knitr
# LazyData: true
# NeedsCompilation: no
# Packaged: 2020-01-28 20:43:59 UTC; erichare
# Author: Heike Hofmann [aut], Eric Hare [aut, cre], GGobi Foundation [aut]
# Maintainer: Eric Hare <eric@oaiti.org>
# Repository: CRAN
# Date/Publication: 2020-01-28 21:40:07 UTC
