{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gglogo
  version: {{ version|replace("-", "_") }}

source:
  fn: gglogo_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gglogo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gglogo/gglogo_{{ version }}.tar.gz
  sha256: 97e05924204b739266264b40da209653dded91d17e52dc7c5f320f349553127b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-knitr
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-reshape2
  run:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.0.0
    - r-jpeg
    - r-knitr
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-reshape2

test:
  commands:
    - $R -e "library('gglogo')"           # [not win]
    - "\"%R%\" -e \"library('gglogo')\""  # [win]

about:
  home: https://github.com/heike/gglogo
  license: GPL-3
  summary: Visualize sequences in (modified) logo plots. The design choices used by these logo
    plots allow sequencing data to be more easily analyzed. Because it is integrated
    into the 'ggplot2' geom framework, these logo plots support native features such
    as faceting.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
