# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "r6ywS+LKjeLWVg8ug8OEVsrRgC0C0zpHvmqaBNrOHsnTfqCpgxRyWaEOEd1+BzcrnJUikXBidvuB67m7jbXJF273zhTVksRcfWLF9UKWYWjsXCA7gGEAfVZkqbaUHtj73E95Gc76Fl2kVt6Xii+PY+T5cFeKGuTmHKVCkV4zVu9TwdOortaHcwFXIdiuoToRFCRjLmTWfenoCgZRjAVto96oEzYXMuSp66EGJQuCFJIMim5JGpnHchBcX8P/AsTaVXKKix912g9ckecFRu0MtcgR9cDx1kDRCowVEV1LHQxvqJiXTZTDIiOIjvIOdgoFbs5PRDAViHiPVi7DD/iDZQ8O3POdnerEfeCyc8+0E1KGmOW+zU+N1bkR0cxPvRd+aX2n6nux+1S5/q6+Z9OT7HAfvdQL4lPH4PRzIbpmtZ09GgA6vXSxrJIAYMZKmeRk3FpBbDXJeVbm3ndhb49nsPQyzi2RypDav7WSdCZRydSAyMEU3Xklm0/8+oM5f47idjn8GY1tHEdDCVdXibO28bC58ocXplkQ7z1dM03nIvcq2HaMgM1BM4I9pRPes9EHYRw69m9lXO5j7yQaoc8kmxYxpcBd4Cfp35aMMcZMgxx/UklQ5a1bzKcBs4lDVB71IrwO0ds6LV65YNYxQeJ4MzA7NCEeSH/uoY2LWbC5Xtc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
